apiVersion: apps/v1
kind: Deployment
metadata:
  name: hokkori
  namespace: hokkori
  labels:
    app: hokkori
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hokkori
  template:
    metadata:
      labels:
        app: hokkori
    spec:
      containers:
        - name: hokkori
          image: kix.ocir.io/nro0opflyunj/hokkori/hokkori:d458d6f
          command: ["./bin/hokkori"]
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ocirsecret
